### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MohammadAsadolahi** [vitchyr/viskit#22]
[2022-06-15 02:41:21,702] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "C:\Users\Aguh\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Aguh\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Aguh\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Aguh\AppData\Local\Programs\Python\Python39\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\Aguh\Downloads\vs\viskit\frontend.py", line 925, in index
    plot_div = get_plot_instruction(plot_keys=plot_keys)
  File "C:\Users\Aguh\Downloads\vs\viskit\frontend.py", line 421, in get_plot_instruction
    plot_height = 300 * len(plot_keys)
TypeError: object of type 'NoneType' has no len()
127.0.0.1 - - [15/Jun/2022 02:41:26] "GET / HTTP/1.1" 500 -

**Comment by YiqiJ** [comment]
encountering the same issue.

**Comment by faker52** [comment]
encountering the same issue.

**Comment by faker52** [comment]
encountering the same issue. how to do?

**Comment by Warggr** [comment]
I had the same issue. But for some reason, running the script as `python -m viskit.frontend path/to/log` works
